name: Arm
on:
  push:
    paths:
      - '.github/workflows/arm-demo.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: ['1.19', '1.20', '1.21', '1.22.2']
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
      - run: |
          go version
  docker_info:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Get Docker System Info
        run: docker system info | grep -E 'Username|Registry'

  windows:
    runs-on: windows-11-arm
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: |
          Get-PSDrive
      - run: |
          $env:Path
      - run: |
          Get-ChildItem env:
      - run: |
          Get-Content "C:\imagedata.json"
      - run: |
          Get-ChildItem "C:\Users\runneradmin"
    

        

          
